m6-django/proyecto_vehiculos_django/proyecto_vehiculos_django/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('vehiculo/', include('vehiculo.urls'),name='vehiculo'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

m6-django/proyecto_vehiculos_django/vehiculo/urls.py
from django.urls import path
from . import views

app_name = "vehiculo"

urlpatterns = [
    path("add/", views.add, name='add'),
    path("catalog/", views.catalog, name='catalog'),
]

m6-django/proyecto_vehiculos_django/vehiculo/models.py
from django.db import models

class Vehiculo(models.Model):
    MARCA_CHOICES = [
        ('FORD', 'Ford'),
        ('CHEVROLET', 'Chevrolet'),
        ('TOYOTA', 'Toyota'),
        ('FIAT', 'Fiat'),
    ]
    CATEGORIA_CHOICES = [
        ('PARTICULAR', 'Particular'),
        ('TRANSPORTE', 'Transporte'),
        ('CARGA', 'Carga'),
    ]
    marca = models.CharField(max_length=20, choices=MARCA_CHOICES, default='FORD')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, choices=CATEGORIA_CHOICES, default='PARTICULAR')
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    
    class Meta:
        permissions = [
            ('can_see_catalog', 'Puede ver el catálogo de vehículos'),
        ]

m6-django/proyecto_vehiculos_django/proyecto_vehiculos_django/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label="Email Address",
        widget=forms.EmailInput(attrs={'type': 'email'}),
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            permission = Permission.objects.get(codename='can_see_catalog')
            user.user_permissions.add(permission)
        return user
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este email ya está en uso.")
        return email

m6-django/proyecto_vehiculos_django/vehiculo/forms.py
from django import forms
from .models import Vehiculo

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['marca', 'modelo', 'serial_carroceria', 'serial_motor', 'categoria', 'precio']
        widgets = {
            'marca': forms.Select(attrs={'class': 'form-select'}),
            'modelo': forms.TextInput(attrs={'class': 'form-control'}),
            'serial_carroceria': forms.TextInput(attrs={'class': 'form-control'}),
            'serial_motor': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-select'}),
            'precio': forms.TextInput(attrs={'class': 'form-control'}),
        }

m6-django/proyecto_vehiculos_django/proyecto_vehiculos_django/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CustomUserCreationForm
from django.contrib import messages

def signup(request):
    form = CustomUserCreationForm(request.POST or None)
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    
    context = {"form": form}        
    return render(request, "../templates/signup.html", context)

def user_login(request):
    
    for message in messages.get_messages(request):
        if message.message == "no permission":
            context = {"error": "no permission"}
            return render(request, "../templates/login.html", context)
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("index")
        else:
            context = {"error": "wrong credentials"}
            return render(request, "../templates/login.html", context)
    
    return render(request, "../templates/login.html")


def user_logout(request):
    logout(request)
    return redirect("index")


def index(request):
    return render(request, "../templates/index.html")

m6-django/proyecto_vehiculos_django/vehiculo/views.py
from django.shortcuts import render, redirect
from .forms import VehiculoForm
from .models import Vehiculo
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def add(request):
    if not request.user.has_perm('vehiculo.add_vehiculo'):
        messages.error(request, "no permission")
        return redirect('/login')
    
    form = VehiculoForm(request.POST or None)
    if request.method == "POST":
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("index")
    context = {"form": form}
    return render(request, 'add.html', context)

@login_required
def catalog(request):
    context = {"vehiculos": Vehiculo.objects.all()}
    return render(request, 'catalog.html', context)

m6-django/proyecto_vehiculos_django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %}🚘 Vehículos{% endblock title %}</title>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
			crossorigin="anonymous"
		/>
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
	</head>
	<body class="container">
		{% include "navbar.html" %}
		<div class="container">
			{% block page_content %} {% endblock page_content %}
		</div>
		<div class="air-gap-medium">{% include "footer.html" %}</div>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
			crossorigin="anonymous"
		></script>
	</body>
</html>

m6-django/proyecto_vehiculos_django/templates/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">
	<footer class="text-center text-lg-start">
		<section class="">
			<div class="container text-center text-md-start mt-5">
				<div class="row mt-3">
					<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
						<h6 class="text-uppercase fw-bold">Descripción</h6>
						<hr
							class="mb-4 mt-0 d-inline-block mx-auto"
							style="width: 60px; background-color: #7c4dff; height: 2px"
						/>
						<p>
							Un sitio web muy genial para ver vehículos. ¡Disfrútalo!
						</p>
					</div>

					<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
						<!-- Links -->
						<h6 class="text-uppercase fw-bold">Aplicaciones</h6>
						<hr
							class="mb-4 mt-0 d-inline-block mx-auto"
							style="width: 60px; background-color: #7c4dff; height: 2px"
						/>
						<p>
							<a href="{% url 'vehiculo:catalog' %}">Catálogo de vehículos</a>
						</p>
					</div>

					<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
						<!-- Links -->
						<h6 class="text-uppercase fw-bold">Contacto</h6>
						<hr
							class="mb-4 mt-0 d-inline-block mx-auto"
							style="width: 60px; background-color: #7c4dff; height: 2px"
						/>
						<p><i class="fas fa-home mr-3"></i> Villarrica, Chile</p>
						<p><i class="fas fa-envelope mr-3"></i> arminescano@gmail.com</p>
					</div>
				</div>
			</div>
		</section>

		<!-- Copyright -->
		<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
			© 2024 Copyright
		</div>
		<!-- Copyright -->
	</footer>
</div>

m6-django/proyecto_vehiculos_django/templates/index.html
{% extends "base.html" %} {% block page_content %}
<header class="vh-100-minus-navbar d-flex justify-content-center align-items-center">
	<div class="px-0 md-px-5">
		<h1 class="display-3">Vehículos kawaii 🚘🏍️</h1>
	</div>
</header>
{% endblock page_content %}

m6-django/proyecto_vehiculos_django/templates/login.html
{% extends "base.html" %} {% block page_content %}
<h1>Iniciar sesión</h1>
<div class="air-gap-xsmall"></div>
{% if error == 'wrong credentials' %}
<div class="alert alert-danger" role="alert">
	<span>Credenciales incorrectas.</span>
</div>
{% endif %}

{% if error == 'no permission' %}
<div class="alert alert-danger" role="alert">
	<span>No tienes los permisos necesarios para acceder a esta página.</span>
</div>
{% endif %}

<div class="air-gap-xsmall"></div>
<form method="post">
	{% csrf_token %}
	<div class="mb-3">
		<label for="username" class="form-label">Usuario</label>
		<input type="text" class="form-control" id="username" name="username" />
	</div>
	<div class="mb-3">
		<label for="password" class="form-label">Contraseña</label>
		<input type="password" class="form-control" id="password" name="password" />
	</div>

	<button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock page_content %}

m6-django/proyecto_vehiculos_django/templates/navbar.html
<nav class="navbar navbar-expand-lg">
	<div class="container-fluid">
		<a class="navbar-brand" href="#">Vehículos</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-3">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'index' %}">Inicio</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'vehiculo:catalog' %}"
						>Catálogo de vehículos</a
					>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'vehiculo:add' %}">Añade vehiculo</a>
				</li>
				{% endif %}
			</ul>

			{% if user.is_authenticated %}
			<ul class="navbar-nav ms-auto mb-2 mb-lg-0 gap-3">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">Salir</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Hola, {{ user.username }}</a>
				</li>
			</ul>
			{% else %}
			<ul class="navbar-nav ms-auto mb-2 mb-lg-0 gap-3">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'login' %}">Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
				</li>
			</ul>
			{% endif %}
		</div>
	</div>
</nav>

m6-django/proyecto_vehiculos_django/templates/signup.html
{% extends "base.html" %}
{% block page_content %}
<h1>Registrarse</h1>
<div class="air-gap-xsmall"></div>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="{{ form.username.id_for_label }}" class="form-label">Nombre de usuario</label>
        <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}">
        {% if form.username.errors %}
            <div class="alert alert-danger">
                {% for error in form.username.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
        
    </div>

    <div class="mb-3">
        <label for="{{ form.email.id_for_label }}" class="form-label">Correo</label>
        <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name}}" value="{{ form.email.value|default_if_none:'' }}">
        {% if form.email.errors %}
            <div class="alert alert-danger">
                {% for error in form.email.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    
    <div class="mb-3">
        <label for="{{ form.password1.id_for_label }}" class="form-label">Contraseña</label>
        <input type="password" class="form-control" id="{{ form.password1.id_for_label }}" name="{{ form.password1.name }}" value="{{ form.password1.value|default_if_none:'' }}">
        {% if form.password1.errors %}
            <div class="alert alert-danger">
                {% for error in form.password1.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
        
    </div>
    
    <div class="mb-3">
        <label for="{{ form.password2.id_for_label }}" class="form-label">Escribe la misma contraseña</label>
        <input type="password" class="form-control" id="{{ form.password2.id_for_label }}" name="{{ form.password2.name }}" value="{{ form.password2.value|default_if_none:'' }}">
        {% if form.password2.errors %}
            <div class="alert alert-danger">
                {% for error in form.password2.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>
<h5 class="mt-3">¿Ya tienes una cuenta? <a href="{% url 'login' %}">Login</a></h5>
{% endblock page_content %}