m7-django-data-access/buena_mesa/buena_mesa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name="inicio"),
    path('reservas/', include('reserva_mesa.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

m7-django-data-access/buena_mesa/reserva_mesa/urls.py
from django.urls import path, include
from . import views

app_name = 'reserva_mesa'

urlpatterns = [
    path('', views.reservar, name="reservar"),
    path('crear_cliente/', views.crear_cliente, name="crear_cliente"),
]

m7-django-data-access/buena_mesa/control_usuario/models.py
from django.db import models

# Create your models here.

m7-django-data-access/buena_mesa/genera_reporte/models.py
from django.db import models

# Create your models here.

m7-django-data-access/buena_mesa/gestion_pago/models.py
from django.db import models

# Create your models here.

m7-django-data-access/buena_mesa/gestion_pedido/models.py
from django.db import models

# Create your models here.

m7-django-data-access/buena_mesa/gestion_producto/models.py
from django.db import models

# Create your models here.

m7-django-data-access/buena_mesa/reserva_mesa/models.py
from django.db import models

class Cliente(models.Model):
    rut = models.CharField(max_length=10, unique=True, default='11111111-1')
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(max_length=15)
    email = models.EmailField()
    direccion = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.nombre} {self.apellido}'
    
class Mesa(models.Model):
    numero = models.IntegerField()
    capacidad = models.IntegerField()
    ocupada = models.BooleanField(default=False)

    def __str__(self):
        return f'Mesa {self.numero}'
    
class Reserva(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE)
    fecha = models.DateField()
    hora = models.TimeField()
    creado_en = models.DateTimeField(auto_now_add=True)
    cantidad_personas = models.IntegerField()

    def __str__(self):
        return f'Reserva de {self.cliente} para {self.cantidad_personas} personas'

m7-django-data-access/buena_mesa/reserva_mesa/forms.py
from django import forms
from .models import Cliente, Mesa, Reserva

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['cliente', 'fecha', 'hora', 'cantidad_personas','mesa']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),
            'hora': forms.TimeInput(attrs={'type': 'time'}),
        }

m7-django-data-access/buena_mesa/buena_mesa/views.py
from django.shortcuts import render

def inicio(request):
    return render(request, "inicio.html")

m7-django-data-access/buena_mesa/reserva_mesa/views.py
from django.shortcuts import render, redirect
from .forms import ClienteForm, ReservaForm
from .models import Cliente, Mesa, Reserva

def reservar(request):
    if request.method == 'POST':
        
        if request.POST.get('mesa'):
            pass
        
        if request.POST.get('hora'):
            fecha = request.POST.get('fecha')
            hora = request.POST.get('hora')
            cantidad_personas = request.POST.get('cantidad_personas')
            reservas_libres = Reserva.objects.filter(fecha__exact=fecha ,capacidad__gte=cantidad_personas, hora__)
            reserva_form = ReservaForm(request.POST)
            reserva_form.fields['mesa'].queryset = mesas_libres
            context = {"reserva_form": reserva_form}
            return render(request, 'reserva_mesa/reservar.html', context)
        #     id_hora = request.POST.get('id_hora')
        #     mesa = Mesa.objects.get(id=id_hora)
        #     context = {"mesa": mesa, "reserva_form": ReservaForm()}
        #     return render(request, 'reserva_mesa/reservar.html', context)
            
        # form = ReservaForm(request.POST)
        # if form.is_valid():
        #     reserva = form.save(commit=False)
        #     reserva.save()
        #     mesa = reserva.mesa
        #     mesa.ocupada = True
        #     mesa.save()
        #     return redirect('reserva_mesa:reservar')
        
        rut = request.POST.get('rut')
        cliente = Cliente.objects.filter(rut=rut).first()
        if cliente is None:
            return redirect('reserva_mesa:crear_cliente')
        else:
            context = {"cliente": cliente}
            return render(request, 'reserva_mesa/reservar.html', context)
    
    return render(request, 'reserva_mesa/reservar.html')

def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reserva_mesa:reservar')
    context = {"crear_cliente_form": ClienteForm()}
    return render(request, 'reserva_mesa/crear_cliente.html', context)

m7-django-data-access/buena_mesa/templates/reserva_mesa/crear_cliente.html
{% extends "base.html" %} {% block page_content %}
<header class="">
	<div class="px-0 md-px-5">
		<h1 class="display-3">Crear cliente ➕💁‍♂️</h1>
	</div>
</header>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{  crear_cliente_form.as_p }}
                <button type="submit" class="btn btn-primary">Crear</button>
            </form>
        </div>
    </div>
{% endblock page_content %}

m7-django-data-access/buena_mesa/templates/reserva_mesa/reservar.html
{% extends "base.html" %} {% block page_content %}
<header class="">
	<div class="px-0 md-px-5">
		<h1 class="display-3">Reservar mesa 🍴</h1>
	</div>
</header>
<div class="container">
	<div class="row">
		<div class="col-md-6">

			{% if cliente %}
			<div class="col-md-6">
				<h2>Cliente</h2>
				<p>{{ cliente.nombre }} {{ cliente.apellido }}</p>
				<p>{{ cliente.telefono }}</p>
				<p>{{ cliente.email }}</p>
			</div>
			<form method="post">
				{% csrf_token %}
				<div>
                    <input type="hidden" name="cliente" required id="id_cliente" value="{{ cliente.id }}">
				</div>

				<div>
					<label for="id_fecha">Fecha:</label>
					<input type="date" name="fecha" required id="id_fecha" />
				</div>

				<div>
					<label for="id_hora">Hora:</label>
					<input type="time" name="hora" required id="id_hora" />
				</div>

				<div>
					<label for="id_cantidad_personas">Cantidad personas:</label>
					<input
						type="number"
						name="cantidad_personas"
						required
						id="id_cantidad_personas"
					/>
				</div>

				<button type="submit" class="btn btn-primary">Buscar mesa</button>
			</form>

            {% elif reserva_form %}
            <form method="post">
                {% csrf_token %}
                {{ reserva_form.as_p }}
                <button type="submit" class="btn btn-primary">Reservar</button>
            </form>

			{% else %}

			<form method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="rut" class="form-label">Rut</label>
					<input
						type="text"
						class="form-control"
						id="rut"
						name="rut"
						required
						maxlength="10"
					/>
				</div>
				<button type="submit" class="btn btn-primary">Buscar</button>
			</form>

			{% endif %}
		</div>
	</div>
	{% endblock page_content %}
</div>